appConfig:
  logLevel: debug
  apiPort: :9090
  contextTimeOut: 5
  timeZone: Etc/UTC
  latencyWarningSec: 3

featureFlag:
  enableDB: false
  enableExcludeUrl: true

database:
  host: localhost
  port: 3307
  username: user
  password: root
  name: article
  debug: true # log sql query
  maxIdleConnections: 0 #0, no idle connections are retained.
  maxConnectionLifetimeSecs: 0 #0, connections are not closed due to a connection's age.
